# edition = "2021"

format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true

match_arm_blocks = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
condense_wildcard_suffixes = true
unstable_features = true
imports_granularity = "Module"
